version: 2

models:
  - name: stg_users
    description: "Standardized user data from raw source"
    columns:
      - name: user_id
        description: "Unique user identifier"
        tests:
          - unique
          - not_null
      - name: country
        description: "User's country"
      - name: _loaded_at
        description: "Timestamp when data was loaded into staging"

  - name: stg_transactions
    description: "Standardized transaction data from raw source"
    columns:
      - name: transaction_id
        description: "Unique transaction identifier"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "User who made the transaction"
        tests:
          - not_null
          - relationships:
              to: ref('stg_users')
              field: user_id
      - name: amount
        description: "Transaction amount in USD"
        tests:
          - not_null
      - name: transaction_date
        description: "Transaction date"
        tests:
          - not_null
      - name: product
        description: "Product vertical"
        tests:
          - accepted_values:
              values: ['bnpl', 'food_delivery', 'ride_sharing', 'gaming']
      - name: status
        description: "Transaction status"
        tests:
          - accepted_values:
              values: ['Completed', 'Pending', 'Failed', 'Cancelled']
      - name: _loaded_at
        description: "Timestamp when data was loaded into staging"

  - name: stg_events
    description: "Standardized event data from raw source"
    columns:
      - name: event_id
        description: "Unique event identifier"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "User who triggered the event"
        tests:
          - not_null
      - name: event_timestamp
        description: "Event timestamp"
        tests:
          - not_null
      - name: event_type
        description: "Type of event"
        tests:
          - accepted_values:
              values: ['login', 'view', 'click', 'purchase', 'logout', 'signup', 'search']
