version: 2

sources:
  - name: raw_data
    description: "Raw CSV files"
    database: dev
    schema: main
    
    tables:
      - name: users
        identifier: "read_csv_auto('data/raw/users.csv', header=true)"
      - name: transactions
        identifier: "read_csv_auto('data/raw/transactions.csv', header=true)"
      - name: events
        identifier: "read_csv_auto('data/raw/events.csv', header=true)"
