version: 2

models:
  - name: dim_users
    description: "Customer dimension with lifetime metrics"
    columns:
      - name: user_id
        tests:
          - unique
          - not_null
      - name: lifetime_gmv
        description: "Total GMV from completed transactions"

  - name: fct_activation
    description: "First transaction analysis by user and product"
    columns:
      - name: user_id
        tests:
          - not_null
      - name: product
        tests:
          - not_null

  - name: fct_transactions
    description: "Transaction facts with customer context"
    columns:
      - name: transaction_id
        tests:
          - unique
          - not_null

  - name: fct_retention
    description: "Monthly cohort retention tracking"
    columns:
      - name: user_id
        tests:
          - not_null

  - name: dim_users_enhanced
    description: "Enhanced user dimension with RFM segmentation"
    columns:
      - name: user_id
        tests:
          - unique
          - not_null
      - name: customer_tier
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['VIP', 'High Value', 'Regular', 'Low Value', 'Inactive']

  - name: fct_transactions_incremental
    description: "Incremental transaction facts for scalability"
    columns:
      - name: transaction_id
        tests:
          - unique
          - not_null
