version: 2

models:
  - name: dim_users
    description: "Customer dimension with lifetime value metrics and product adoption"
    columns:
      - name: user_id
        description: "Primary key - unique customer identifier"
        data_tests:
          - unique
          - not_null

  - name: fct_transactions
    description: "Transaction fact table with full customer context"
    columns:
      - name: transaction_id
        description: "Primary key - unique transaction identifier"
        data_tests:
          - unique
          - not_null
      
      - name: user_id
        description: "Foreign key to dim_users"
        data_tests:
          - relationships:
              to: ref('dim_users')
              field: user_id

  - name: fct_activation
    description: "First transaction analysis by user and product"
    columns:
      - name: user_id
        description: "User identifier"
        data_tests:
          - not_null
      
      - name: product
        description: "Product where activation occurred"
        data_tests:
          - not_null

  - name: fct_retention
    description: "Monthly cohort retention metrics by product"
    columns:
      - name: cohort_month
        description: "Month when user first transacted"
        data_tests:
          - not_null
      
      - name: product
        description: "Product line being analyzed"
        data_tests:
          - not_null
