version: 2

models:
  - name: int_user_summary
    description: "Intermediate user-level aggregations"
    columns:
      - name: user_id
        description: "Unique user identifier"
        data_tests:
          - unique
          - not_null

  - name: int_transaction_summary
    description: "Intermediate transaction aggregations"
    columns:
      - name: product
        description: "Product identifier"
        data_tests:
          - not_null
      - name: transaction_date
        description: "Transaction date"
        data_tests:
          - not_null

  - name: int_event_summary
    description: "Intermediate event aggregations"
    columns:
      - name: user_id
        description: "User identifier"
        data_tests:
          - not_null
      - name: event_date
        description: "Event date"
        data_tests:
          - not_null
